export type placeDummy = {
  id?: number;
  name: string;
  address: string;
  capacity_min: number;
  capacity_max: number;
  price: string | null;
  facilities: string[] | [];
  purpose: string[] | [];
  image_url: string;
  images?: string[];
};

export const placeDummies: placeDummy[] = [
  {
    id: 1,
    name: "Gedung Pertemuan Victory",
    address: "Gg. Rais No. 287, Baru Ilir, Balikpapan Barat",
    capacity_min: 300,
    capacity_max: 1000,
    price: "Rp 8 - 16 juta",
    facilities: ["Private Room", "Parkir", "AC Full", "Stage", "Sound System"],
    purpose: ["Meeting", "Conference", "Keluarga", "Pernikahan"],
    image_url: "/gedungvictory.png",
  },
  {
    id: 2,
    name: "Grha Bintang Balikpapan",
    address: "Jl. Cilaki No. 413, Kariangau, Balikpapan Barat",
    capacity_min: 200,
    capacity_max: 2000,
    price: "Rp 5 - 11 juta",
    facilities: ["Parkir Luas", "Catering", "Hall Besar", "AC Central", "Security"],
    purpose: ["Conference", "Keluarga", "Pernikahan", "Pameran"],
    image_url: "/grhabintang.jpeg",
  },
  {
    id: 3,
    name: "Platinum Hotel & Convention Hall",
    address: "Jl. Naripan No. 346, Batu Ampar, Balikpapan Barat",
    capacity_min: 200,
    capacity_max: 3000,
    price: "Rp 6 - 12 juta",
    facilities: ["Hotel", "AC", "Ballroom", "Parkir", "Wi-Fi"],
    purpose: ["Conference", "Pernikahan", "Meeting"],
    image_url: "/Platinum-Hotel-Convention-Hall-Balikpapan-Exterior.png",
  },
  {
    id: 4,
    name: "Balai Sudirman (Gedung Klandasan)",
    address: "Jl. Jenderal Sudirman No. 18, Klandasan Ilir",
    capacity_min: 400,
    capacity_max: 500,
    price: "Rp 7 juta/hari",
    facilities: ["AC", "Hall Medium", "Parkir", "Sound System"],
    purpose: ["Meeting", "Conference", "Pernikahan"],
    image_url: "/balaisudirman.png",
  },
  {
    id: 5,
    name: "OPEN HOUSE",
    address: "Jl. Markoni Atas No.88, Damai",
    capacity_min: 45,
    capacity_max: 45,
    price: "Mulai Rp 300 ribu/jam",
    facilities: ["Private Room", "Parkir", "Wi-Fi", "Proyektor"],
    purpose: ["Meeting", "Birthday", "Gathering"],
    image_url: "/open-house.png",
  },
  {
    id: 6,
    name: "NARA Coffie Brunch",
    address: "Jl. Syarifuddin Yoes No.25, Gn. Bahagia",
    capacity_min: 100,
    capacity_max: 100,
    price: "Mulai Rp 500 ribu / 3 jam",
    facilities: ["Private Room", "Parkir", "Wi-Fi", "Toilet", "AC"],
    purpose: ["Meeting", "Keluarga", "Gathering"],
    image_url: "/nara.png",
  },
  {
    id: 7,
    name: "0412 Coffe",
    address: "Jl. Syarifuddin Yoes No. 25, Depan Hotel Helios, Balikpapan Selatan",
    capacity_min: 30,
    capacity_max: 30,
    price: "Mulai Rp 150 ribu / jam",
    facilities: ["Area Outdoor", "Parkir", "Wi-Fi", "Toilet"],
    purpose: ["Keluarga", "Anak", "Meeting Mini"],
    image_url: "/0412.jpeg",
  },
  {
    id: 8,
    name: "Global Sport Balikpapan",
    address: "Jl. MT Haryono No.33, RT.15, Gunung Samarinda, Balikpapan Utara",
    capacity_min: 100,
    capacity_max: 400,
    price: "Rp 300 ribu – 1 juta / jam",
    facilities: ["Futsal", "Bulu Tangkis", "Basket", "Yoga", "Parkir"],
    purpose: ["Olahraga", "Gathering", "Komunitas"],
    image_url: "/bsc.jpeg",
  },
  {
    id: 9,
    name: "BSCC Dome Balikpapan",
    address: "Jl. Ruhui Rahayu No.1, Sepinggan, Balikpapan Selatan",
    capacity_min: 2500,
    capacity_max: 5000,
    price: "Tergantung paket (Rp 20–80 juta)",
    facilities: ["Parkir Besar", "Hall Kolosal", "Sound System", "Security"],
    purpose: ["Concert", "Pameran", "Turnamen", "Pernikahan Besar"],
    image_url: "/dome.png",
  },
  {
    id: 10,
    name: "Midtown Coffee",
    address: "Jl. Jenderal Sudirman No.79, Gn. Bahagia",
    capacity_min: 40,
    capacity_max: 40,
    price: "Mulai Rp 250 ribu / jam",
    facilities: ["Wi-Fi", "Toilet", "Bar", "Parkir Gratis", "AC"],
    purpose: ["Keluarga", "Grup", "Meeting", "Nugas"],
    image_url: "/midtown.jpeg",
  },
  {
    id: 11,
    name: "Poto Koffie",
    address: "Jl. H. Tjutjup Suparna Blok F No.3, Damai Baru",
    capacity_min: 60,
    capacity_max: 60,
    price: "Mulai Rp 200 ribu / jam",
    facilities: ["Wi-Fi", "Toilet", "Parkir Gratis", "AC", "Proyektor"],
    purpose: ["Grup", "Keluarga", "Anak", "Meeting"],
    image_url: "/potokoffie.jpeg",
  },
  {
    id: 12,
    name: "Pantai Kemala",
    address: "Jl. Jendral Sudirman, Desa Klandasan Ulu, Balikpapan Kota",
    capacity_min: 1000,
    capacity_max: 1000,
    price: "Tergantung event",
    facilities: ["Pantai", "Parkir", "Toilet", "Outdoor", "Foodcourt"],
    purpose: ["Konser", "Festival", "Gathering Besar", "Piknik"],
    image_url: "/pantaikemala.jpeg",
  },
];
